name: Checkov IaC Scan

on:
 push:
 workflow_dispatch:

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true
          framework: terraform
          hard_fail_on: CKV2_AWS_6,CKV_AWS_24
        
