name: IaC pipeline

on:
 push:
 workflow_dispatch:

jobs:
  iac:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Tf init
        run: |
         terraform init -backend=false
      
      - name: Tf plan
        run: |
         terraform plan -refresh=false
        env:
          AWS_SKIP_CREDENTIALS_VALIDATION: "true"
          AWS_ACCESS_KEY_ID: "mock"
          AWS_SECRET_ACCESS_KEY: "mock"
          AWS_DEFAULT_REGION: "us-east-1"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true
          framework: terraform
          hard_fail_on: CKV_AWS_126,CKV_AWS_24,CKV_AWS_382

      - name: Apply IaC
        run: | 
         echo "apply"
