name: IaC pipeline

on:
 push:
 workflow_dispatch:

jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
      - name: Tf init
        run: |
         terraform init -backend=false
      
      - name: Tf plan
        run: |
         terraform plan -refresh=false
        env:
         AWS_EC2_METADATA_DISABLED: "true"
